[Service]
ExecStart=
ExecStart=/usr/bin/transmission-daemon -g /etc/transmission-daemon -f --log-level=error
UMask=0022
ExecStartPre=/usr/bin/install -o debian-transmission -g debian-transmission -m 600 /etc/transmission-daemon/settings.defaults.json /etc/transmission-daemon/settings.json