#!/bin/sh
set -e

if ! getent group xray-vpn > /dev/null 2>&1; then
    addgroup --system xray-vpn
fi

if ! getent passwd xray-vpn > /dev/null 2>&1; then
    adduser --system --no-create-home --shell /usr/sbin/nologin \
            --ingroup xray-vpn xray-vpn
fi

echo "xray-vpn: set proxy link with: xray-vpn link add <vless://...>"
echo "xray-vpn: to allow a user to control the service, run: usermod -aG xray-vpn <username>"

mkdir -p /run/xray-vpn /var/cache/xray-vpn

chown xray-vpn:xray-vpn /usr/bin/xray-vpnd
chown xray-vpn:xray-vpn /usr/bin/xray-vpn
chown -R xray-vpn:xray-vpn /etc/xray-vpn /run/xray-vpn /var/cache/xray-vpn

chmod 4550 /usr/bin/xray-vpn
chmod 500 /usr/bin/xray-vpnd
chmod 770 /etc/xray-vpn
chmod 700 /run/xray-vpn
chmod 700 /var/cache/xray-vpn

systemctl daemon-reload
systemctl enable xray-vpn.service || true
systemctl enable --now xray-vpn-refresh.timer || true
systemctl restart xray-vpn.service || true
