#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    systemctl stop xray-vpn.service 2>/dev/null || true
    systemctl disable xray-vpn.service 2>/dev/null || true
    systemctl disable --now xray-vpn-refresh.timer 2>/dev/null || true
fi

