#!/bin/sh
# Download xray-vpn binaries to /tmp.
set -e

VERSION="0.1.0"
BASE_URL="https://github.com/realglebivanov/xray-vpn/releases/download/v${VERSION}"
DEST="/tmp"

for bin in xray-vpnd xray-vpn; do
    echo "Downloading ${bin} ..."
    wget -q -O "${DEST}/${bin}" "${BASE_URL}/${bin}-mipsle"
    chmod 755 "${DEST}/${bin}"
done
